/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;

/**
 *
 * @author Jazmin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backg = new javax.swing.JPanel();
        Uesfmo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        exit = new javax.swing.JPanel();
        exitxt = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        usertx = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        passtxt = new javax.swing.JPasswordField();
        entrarbt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Backg.setBackground(new java.awt.Color(255, 255, 255));
        Backg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Uesfmo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Uesfmo.setForeground(new java.awt.Color(255, 255, 255));
        Uesfmo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Uesfmo.setText("UES FMO");
        Uesfmo.setToolTipText("");
        Backg.add(Uesfmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 130, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tienda.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        Backg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 650, 570));

        barra.setBackground(new java.awt.Color(255, 255, 255));

        exit.setBackground(new java.awt.Color(255, 255, 255));

        exitxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitxt.setText("X");
        exitxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitxt, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 946, Short.MAX_VALUE))
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Backg.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        Logo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favicon.png"))); // NOI18N
        Logo.setText("FMOcc");
        Backg.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("INICIAR SESIÓN");
        Backg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        user.setText("USUARIO");
        Backg.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 70, -1));

        usertx.setForeground(new java.awt.Color(204, 204, 204));
        usertx.setText("Ingrese su nombre de usuario");
        usertx.setBorder(null);
        usertx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usertxMousePressed(evt);
            }
        });
        usertx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxActionPerformed(evt);
            }
        });
        Backg.add(usertx, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 260, -1));

        pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pass.setText("CONTRASEÑA");
        Backg.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        passtxt.setForeground(new java.awt.Color(204, 204, 204));
        passtxt.setText("********");
        passtxt.setBorder(null);
        passtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passtxtMousePressed(evt);
            }
        });
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        Backg.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, -1));

        entrarbt.setBackground(new java.awt.Color(0, 134, 190));
        entrarbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRAR");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout entrarbtLayout = new javax.swing.GroupLayout(entrarbt);
        entrarbt.setLayout(entrarbtLayout);
        entrarbtLayout.setHorizontalGroup(
            entrarbtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        entrarbtLayout.setVerticalGroup(
            entrarbtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Backg.add(entrarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Backg, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxActionPerformed

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxtActionPerformed

    private void exitxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitxtMouseClicked

    private void exitxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitxtMouseEntered
        exit.setBackground(Color.red);
    }//GEN-LAST:event_exitxtMouseEntered

    private void exitxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitxtMouseExited
        exit.setBackground(Color.white);
    }//GEN-LAST:event_exitxtMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        entrarbt.setBackground(new Color(0,150,220));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        entrarbt.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_jLabel2MouseExited

    private void usertxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertxMousePressed
        if(usertx.getText().equals("Ingrese su nombre de usuario")){
           usertx.setText("");
           usertx.setForeground(Color.black);
        }
        if(String.valueOf(passtxt.getPassword()).isEmpty()){
           passtxt.setText("********");
           passtxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usertxMousePressed

    private void passtxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passtxtMousePressed
        if(String.valueOf(passtxt.getPassword()).equals("********")){
           passtxt.setText("");
           passtxt.setForeground(Color.black); 
           
        }
        if(usertx.getText().isEmpty()){
           usertx.setText("Ingrese su nombre de usuario");
           usertx.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passtxtMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        javax.swing.JOptionPane.showConfirmDialog(this,"Sus datos de login:\n Usuario: " + usertx.getText() + "\nContraseña: " + String.valueOf(passtxt.getPassword()), "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backg;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Uesfmo;
    private javax.swing.JPanel barra;
    private javax.swing.JPanel entrarbt;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel exitxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel user;
    private javax.swing.JTextField usertx;
    // End of variables declaration//GEN-END:variables
}
